name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        uses: ./
        with:
          command: "node ./tests/script.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
